version: '3'

services:
    db:
        image: 'postgres:12-alpine'
        container_name: 'movie-postgres'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '54320:5432'
        volumes:
            - 'pgdata:/var/lib/postgresql/data'

volumes:
    pgdata:
