# Generated by Django 3.0.6 on 2020-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Movie Poster'),
        ),
    ]
